# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: dcarter@txstate.edu
description: "Assistant professor of digital media studying online labor and technology adaptation."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielcarter.github.io"

office_hours: "OM 208 | T 12:30 - 3:30pm, W 9:00 - 11:00am and by appointment"
office_hours_booking: "https://danielcarter.youcanbook.me/"

collections:
  assignments:
    output: true
  topics:
    output: true
  courses:
    output: true
  resources:
    output: true
  lesson_plans:
    output: true
  exercises:
    output: true
  learning_journal:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "courses"
    values:
      layout: "course"
  -
    scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
  -
    scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: ""
      type: "resources"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "learning_journal"
    values:
      layout: "learning_journal"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
